--- a/.github/workflows/test-examples.yml
+++ b/.github/workflows/test-examples.yml
@@ -63,4 +63,4 @@
           #   popd
           # done
           # popd
-          pnpm run test:examples
+          pnpm run test:examples